core:
  service:
    db:
      password: developer
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: sad
      url: jdbc:sqlserver://localhost;databaseName=education
      show-sql: true

encrpytion:
  keystore:
    alias: jwt
    location: classpath:/jwt.jks
    classpath-location: jwt.jks
    password: password
    secret: password

server:
  port: 8081
  servlet:
    context-path: /auth

check-user-scopes: true